Yumbo/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('', include('schedule.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='yumbo-home'),
    # path('about/', views.about, name='yumbo-about'),
    # path('recipes/', views.recipes, name='recipes'),
    path('recipes/<int:recipe_id>', views.recipe_detail, name='recipe-detail'),
    path('create-recipe/', views.create_recipe, name='create-recipe'),
    path('edit-recipe/<int:recipe_id>', views.edit_recipe, name='edit-recipe'),
    path('delete-recipe/<int:recipe_id>', views.delete_recipe, name='delete-recipe'),
]

recipes/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from random import choice
from os.path import join, isfile
from os import listdir

def random_img():
    dir_path = 'media/recipe_pics/defaults'
    files = [content for content in listdir(dir_path) if isfile(join(dir_path, content))]
    return join('recipe_pics/defaults', choice(files))

class Recipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe_name = models.CharField("Recipe Name", max_length=200)
    prep_time = models.CharField("Prep Time", max_length=30)
    image = models.ImageField(default=random_img, upload_to='recipe_pics')

    def __str__(self):
        return self.recipe_name
    
class Ingredient(models.Model):
    UNIT_CHOICES = [('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('lb', 'pound'), ('g', 'gram'), ('cup', 'cup'), ('oz', 'fluid ounce'), ('gal', 'gallon'), ('quart', 'quart'), ('pint', 'pint'), ('mL', 'milliliter'), ('L', 'liter'), ('dash', 'dash'), ('pinch', 'pinch'), ('stick', 'stick'),]

    ingredient_name = models.CharField("Ingredient Name", max_length=100)
    position = models.IntegerField(blank=False)
    quantity = models.DecimalField("Quantity", max_digits=10, decimal_places=5, null=True)
    units = models.CharField(max_length=5, choices=UNIT_CHOICES, blank=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    def __str__(self):
        return self.ingredient_name + ', ' + self.recipe.recipe_name

class Direction(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    position = models.IntegerField(blank=False)
    header = models.CharField("Direction Header", max_length=140)
    text = models.TextField("Instructions", blank=True)

    def __str__(self):
        return str(self.position) + ', ' + self.recipe.recipe_name
        

recipes/forms.py
from django import forms
from .models import Recipe, Ingredient, Direction

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['recipe_name', 'prep_time', 'image']
        widgets = {
            'recipe_name': forms.TextInput(attrs={'class': 'form-control friendly-input', 'placeholder': 'Recipe Name'}),
            'prep_time': forms.TextInput(attrs={'class': 'form-control friendly-input', 'placeholder': 'Prep Time'}),
            'image': forms.FileInput(attrs={'class': 'form-control-file'}),
        }

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['position', 'ingredient_name', 'quantity', 'units']
        widgets = {
            'position': forms.HiddenInput(),
            'ingredient_name': forms.TextInput(attrs={'class': 'form-control friendly-input', 'placeholder': 'Ingredient Name'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control friendly-input'}),
            'units': forms.Select(attrs={'class': 'form-select friendly-input'}),
        }

class DirectionForm(forms.ModelForm):
    class Meta:
        model = Direction
        fields = ['position', 'header', 'text']
        widgets = {
            'position': forms.HiddenInput(),
            'header': forms.TextInput(attrs={'class': 'form-control friendly-input'}),
            'text': forms.Textarea(attrs={'class': 'form-control friendly-input', 'rows': 4})
        }

recipes/views.py
#TODO: Turn base directory into a landing page if not logged in, but a user home page if they are logged in? See how this might affect performance.

from django.shortcuts import render, redirect, get_object_or_404
from django.forms import inlineformset_factory
from .models import Recipe, Ingredient, Direction
from .forms import RecipeForm, IngredientForm, DirectionForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404

@login_required
def home(request):
    context = {
        'recipes': Recipe.objects.filter(user=request.user),
    }
    return render(request, 'recipes/home.html', context)

# def about(request):
#     return render(request, 'recipes/about.html')

# @login_required
# def recipes(request):
#     #creating this view in the event that our home dashboard differs from a recipe focused view
#     context = {
#         'recipes': Recipe.objects.filter(user=request.user),
#     }
#     return render(request, 'recipes/home.html', context)

@login_required
def recipe_detail(request, recipe_id):
    context = {
        'recipe': Recipe.objects.get(user=request.user, pk=recipe_id),
        'ingredients': Ingredient.objects.filter(recipe=recipe_id),
        'directions': Direction.objects.filter(recipe=recipe_id).order_by('position'),
    }
    if context['recipe']:
        return render(request, 'recipes/recipe_detail.html', context)
    else:
        raise Http404('You shouldn\'t be here...')

@login_required
def create_recipe(request):
    if request.method == "POST":
        recipe_form = RecipeForm(request.POST, request.FILES)
        ingredient_formset = inlineformset_factory(Recipe, Ingredient, form=IngredientForm, can_delete=True)
        ingredient_forms = ingredient_formset(request.POST)
        direction_formset = inlineformset_factory(Recipe, Direction, form=DirectionForm, can_delete=True)
        direction_forms = direction_formset(request.POST)
        print("POST")
        if recipe_form.is_valid() and ingredient_forms.is_valid() and direction_forms.is_valid():
            recipe = recipe_form.save(False)
            recipe.user = request.user
            recipe.save()

            ingredients = ingredient_forms.save(False)
            for ingredient in ingredients:
                ingredient.recipe = recipe
                ingredient.save()

            directions = direction_forms.save(False)
            for direction in directions:
                direction.recipe = recipe
                direction.save()

            return redirect('recipe-detail', recipe_id=recipe.pk)
    else:
        recipe_form = RecipeForm()
        ingredient_formset = inlineformset_factory(Recipe, Ingredient, form=IngredientForm, extra=1)
        ingredient_forms = ingredient_formset(initial=[{'position':0}])
        direction_formset = inlineformset_factory(Recipe, Direction, form=DirectionForm, extra=1)
        direction_forms = direction_formset(initial=[{'position':0}])

    context = {
        'recipe_form': recipe_form,
        'ingredient_forms': ingredient_forms,
        'direction_forms': direction_forms,
    }

    return render(request, 'recipes/recipe_form.html', context)

@login_required
def edit_recipe(request, recipe_id):
    recipe_instance = get_object_or_404(Recipe, pk=recipe_id)
    ingredient_formset = inlineformset_factory(Recipe, Ingredient, form=IngredientForm, extra=0, can_delete=True)
    direction_formset = inlineformset_factory(Recipe, Direction, form=DirectionForm, extra=0, can_delete=True)

    if request.method == "POST":
        recipe_form = RecipeForm(request.POST, request.FILES, instance=recipe_instance)
        ingredient_forms = ingredient_formset(request.POST, instance=recipe_instance)
        direction_forms = direction_formset(request.POST, instance=recipe_instance)

        if recipe_form.is_valid() and ingredient_forms.is_valid() and direction_forms.is_valid():
            recipe = recipe_form.save()

            ingredients = ingredient_forms.save(False)
            for ingredient in ingredient_forms.deleted_objects:
                ingredient.delete()
            for ingredient in ingredients:
                ingredient.recipe = recipe
                ingredient.save()

            directions = direction_forms.save(False)
            for direction in direction_forms.deleted_objects:
                direction.delete()
            for direction in directions:
                direction.recipe = recipe
                direction.save()

            return redirect('recipe-detail', recipe_id=recipe.pk)
    else:
        recipe_form = RecipeForm(instance=recipe_instance)
        ingredient_formset = inlineformset_factory(Recipe, Ingredient, form=IngredientForm, extra=0)
        ingredient_forms = ingredient_formset(instance = recipe_instance)
        direction_formset = inlineformset_factory(Recipe, Direction, form=DirectionForm, extra=0)
        direction_forms = direction_formset(instance=recipe_instance)

    context = {
        'recipe': Recipe.objects.get(user=request.user, pk=recipe_id),
        'recipe_form': recipe_form,
        'ingredient_forms': ingredient_forms,
        'direction_forms': direction_forms,
    }

    return render(request, 'recipes/recipe_form.html', context)

@login_required
def delete_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)

    if request.method == 'POST':
        recipe.delete()
        return redirect('/')

    context = {
        'recipe': recipe
    }

    return render(request, 'recipes/delete_recipe.html', context)

recipes/templates/recipes/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie|Raleway" />

        <link rel="stylesheet" type="text/css" href="{% static 'recipes/recipes.css' %}">
        <script src="{% static 'recipes/recipes.js' %}"></script>

        {% if title %}
            <title>Yumbo - {{ title }}</title>
        {% else %}
            <title>Yumbo</title>
        {% endif %}
    </head>
    <body>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <nav class="navbar navbar-expand-sm navbar-dark sticky-top">
            <a class="navbar-brand ml-3" href="{% url 'yumbo-home' %}"><h1>Yumbo</h1></a>

            <button class="navbar-toggler mr-3 ml-auto" type="button" data-toggle="collapse" data-target="#yumboNavbar">
                <!-- Need to update this icon to a font awesome icon -->
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse ml-3 ml-sm-0 mb-0" id="yumboNavbar">
                <!-- <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="% url 'recipes' %">Recipes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="% url 'calendar' %">Calendar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#">Lists</a>
                    </li>
                </ul> -->


                <!-- We can probably just have one ul tag and have the if statement on the li tag groups -->
                {% if user.is_authenticated %}
                    <form class="search-bar form-inline d-flex my-2 my-lg-0 ml-sm-auto">
                        <input class="form-control mr-2 friendly-input" type="search" placeholder="Search Recipes..." aria-label="Search">
                        <button class="btn custom-btn friendly-btn" type="submit">Search</button>
                    </form>
                    <ul class="navbar-nav mr-3 ml-auto">
                        <!-- <li class="nav-item">
                            <a class="nav-link active" href="% url 'profile' %">Profile</a>
                        </li> -->
                        <li class="nav-item ml-2">
                            <a class="nav-link active" href="{% url 'logout' %}">Log Out</a>
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav mr-3 ml-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'login' %}">Log In</a>
                        </li>
                    </ul>
                {% endif %}
                </div>        
            </div> 
        </nav>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show"{% endif %}>
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </li>
                    
                {% endfor %}
            </ul>
        {% endif %}
        {% block content %}{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
    </body>
</html>

recipes/templates/recipes/delete_recipe.html
{% extends 'recipes/base.html' %}
{% block content %}
    <div class="container rounded my-3">
        <div class="row">
            <div class="col-8 offset-2 container-content rounded px-5 py-3">
                <h1>Are you sure you want to delete {{ recipe.recipe_name}}?</h1>
                <h4>If you change your mind later, you will have to rebuild it from scratch!</h4>
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn custom-btn danger-btn">Yes, Delete This Recipe</button>
                    <a href="{% url 'recipe-detail' recipe.pk %}" class="btn custom-btn friendly-btn">No, Take Me Back!</a>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

recipes/templates/recipes/home.html
{% extends "recipes/base.html" %}
{% block content %}
    <div class="container rounded my-3">
        <div class="row mt-3">
            {% for recipe in recipes %}
                <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                    <a class="recipe-card-link" href="{% url 'recipe-detail' recipe.pk %}">
                        <div class="col">
                            <div class="card mb-3 recipe-card">
                                <img src="{{ recipe.image.url }}" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title">{{recipe.recipe_name}}</h5>
                                    <p class="card-text">{{ recipe.prep_time }}</p>
                                <!--  <a href="{% url 'recipe-detail' recipe.pk %}" class="btn btn-primary">Go somewhere</a> -->
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                <a class="recipe-card-link" href="{% url 'create-recipe' %}">
                    <div class="card mb-3 mt-2 recipe-card" id="new-recipe-card">
                            <svg viewBox="0 0 16 16" class="bi bi-plus-circle mx-auto my-5" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
                                <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
                                <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                            </svg>
                            <h5 class="card-title mb-4">Add New Recipe</h5>

                    </div>
                </a>
            </div>
        </div>
    </div>
    {% endblock content %}

recipes/templates/recipes/recipe_detail.html
{% extends "recipes/base.html" %}
{% block content %}
    <div class="container container-content container-skinny rounded my-3">
        <div class="row mt-3">
            <div class="col">
                <h1 class="recipe-header">{{ recipe.recipe_name }}</h1>
            </div>

            <div class="col-md-6 offset-md-0">
                <a href="{% url 'delete-recipe' recipe.pk %}" class="btn btn-lg custom-btn danger-btn float-md-right ml-md-1 mt-2 order-xs-2 order-md-1">Delete Recipe</a>
                <a href="{% url 'edit-recipe' recipe.pk %}" class="btn btn-lg custom-btn friendly-btn float-md-right mt-2 order-xs-1 order-md-2">Edit Recipe</a>
            </div>

        </div>
        <p>
            Prep time: {{ recipe.prep_time }}
        </p>
        <hr>
        <img src="{{ recipe.image.url }}" alt="" class="fit-image-profile mb-4">

        <h2>Ingredients:</h2>
            <ul class="ingredients">
                {% for ingredient in ingredients %}
                    <li class="mb-1">
                        <input type="checkbox" class="strikethrough" name="ingredient-check-{{ forloop.counter0 }}"></input>
                        <label class="ingredient-item" for="ingredient-check-{{ forloop.counter0 }}"> {{ ingredient.ingredient_name }}, {{ ingredient.quantity.normalize }} {{ ingredient.units }}</label>
                    </li>
                {% endfor %}
            </ul>
        <ol class="direction-list">
            {% for direction in directions %}
                <li class="direction-item">
                    <h3>{{ direction.header }}</h3>
                    <p>{{ direction.text }}</p>
                </li>
            {% endfor %}
        </ol>
    </div>
{% endblock content %}

recipes/templates/recipes/recipe_form.html
{% extends 'recipes/base.html' %}
{% block content %}
    <div class="container container-content rounded my-2"">
        <div class="row mt-3">
            {% if recipe %}
                <h1 class="recipe-header">Update Recipe - {{ recipe.recipe_name }}</h1>
            {% else %}
                <h1 class="recipe-header">Create New Recipe</h1>
            {% endif %}
        </div>
        <hr>
        <form enctype="multipart/form-data" method="POST" class="recipe-form">
            {% csrf_token %}
            <h3>Recipe Details</h3>
            <div class="form-group">
                <div class="form-group row">
                    {{ recipe_form.recipe_name.errors }}
                    <label for="id_recipe_name">Recipe Name:</label>
                    <div class="col-6">
                        {{ recipe_form.recipe_name }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ recipe_form.prep_time.errors }}
                    <label for="id_recipe_name">Prep Time:</label>
                    <div class="col-6">
                        {{ recipe_form.prep_time }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ recipe_form.image.errors }}
                    <label for="id_recipe_name">Image:</label>
                    <div class="col-6">
                        {{ recipe_form.image }}
                    </div>
                </div>
            </div>
            <hr>
            <h3>Ingredients</h3>
            {{ ingredient_forms.management_form }}
            <div id="ingredients-form-container" class="form-group">
                {% for ingredient_form in ingredient_forms %}
                <div id="ingredient-{{ forloop.counter0 }}" class="mb-3">
                    <div class="form-group row">
                        {{ ingredient_form.id }}
                        {{ ingredient_form.errors }}
                        {{ ingredient_form.position }}
                        <div class="col-md-4 col-6">
                            <label for="ingredient_form.ingredient_name">Ingredient Name:</label>
                            {{ ingredient_form.ingredient_name }}
                        </div>
                        <div class="col-md-2 col-3">
                            <label for="ingredient_form.quantity">Quantity:</label>
                            {{ ingredient_form.quantity }}
                        </div>
                        <div class="col-md-2 col-3">
                            <label for="ingredient_form.units">Units:</label>
                            {{ ingredient_form.units }}
                        </div>
                        {{ ingredient_form.DELETE }}
                        <div class="col-md-4">
                            <a href="#" id="delete-ingredient-button-{{ forloop.counter0 }}" class="btn custom-btn danger-btn mt-md-4">Remove Ingredient</a>
                        </div>             
                        <script type="text/javascript">deleteModelForm("ingredient", "{{ forloop.counter0 }}")</script>
                    </div>
                </div>
                {% endfor %}
            </div>
            <a href="#" id="add-ingredient-button" class="btn custom-btn friendly-btn add-ingredient">Add Ingredient</a>
            <template id="new-ingredient-form-template">
                <div id="new-ingredient-form" class="mb-3">
                    <div class="form-group row">
                        {{ ingredient_form.id }}
                        {{ ingredient_form.errors }}
                        {{ ingredient_forms.empty_form.position }}
                        <div class="col-md-4 col-6">
                            <label for="ingredient_form.ingredient_name">Ingredient Name:</label>
                            {{ ingredient_forms.empty_form.ingredient_name }}
                        </div>
                        <div class="col-md-2 col-3">
                            <label for="ingredient_form.quantity">Quantity:</label>
                            {{ ingredient_forms.empty_form.quantity }}
                        </div>
                        <div class="col-md-2 col-3">
                            <label for="ingredient_form.units">Units:</label>
                            {{ ingredient_forms.empty_form.units }}
                        </div>
                        <input type="checkbox" name="ingredient_set-__prefix__-DELETE" id="id_ingredient_set-__prefix__-DELETE">
                        <div class="col-md-4">
                            <a href="#" id="delete-ingredient-button-__prefix__" class="btn custom-btn danger-btn mt-md-4">Remove Ingredient</a>
                        </div>
                        <script type="text/javascript">deleteModelForm("ingredient", "__prefix__")</script>
                    </div>
                </div>
            </template>
            <script type="text/javascript">newModelForm("ingredient")</script>
            <hr>
            <h3>Directions</h3>
            <div class="row">
                <div class="col-lg-8">
                    {{ direction_forms.management_form }}
                    <ol id="directions-form-container" class="direction-list form-group">
                        {% for direction_form in direction_forms %}
                        <li id="direction-{{ forloop.counter0 }}" class="direction-item mb-4">
                                    <div class="form-group row">
                                        {{ direction_form.id }}
                                        {{ direction_form.errors }}
                                        {{ direction_form.position }}
                                        <div class="col-md-8">
                                            <label for="direction_form.header">Header:</label>
                                            {{ direction_form.header }}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-12">
                                            <label for="direction_form.text">Text:</label>
                                            {{ direction_form.text }}
                                        </div>
                                    </div>
                                        {{ direction_form.DELETE }}
                                        <a href="#" id="delete-direction-button-{{ forloop.counter0 }}" class="btn custom-btn danger-btn">Remove Direction</a>
                                        <script type="text/javascript">deleteModelForm("direction", "{{ forloop.counter0 }}")</script>
                        </li>
                        {% endfor %}
                    </ol>
                    <a href="#" id="add-direction-button" class="btn custom-btn friendly-btn add-direction">Add Direction</a>
                </div>
            </div>

            <template id="new-direction-form-template">
                <li id="new-direction-form" class="direction-item mb-4">
                    <div class="form-group row">
                        {{ direction_forms.empty_form.id }}
                        {{ direction_forms.empty_form.position }}
                        <div class="col-md-8">
                            <label for="direction_form.header">Header:</label>
                            {{ direction_forms.empty_form.header }}
                        </div>
                    </div>
                        <div class="form-group row">
                            <div class="col-md-12">
                                <label for="direction_form.text">Text:</label>
                                {{ direction_forms.empty_form.text }}
                            </div>
                        </div>
                        <input type="checkbox" name="direction_set-__prefix__-DELETE" id="id_direction_set-__prefix__-DELETE">
                        <a href="#" id="delete-direction-button-__prefix__" class="btn custom-btn danger-btn">Remove Direction</a>
                        <script type="text/javascript">deleteModelForm("direction", "__prefix__")</script>
                </li>
            </template>
            <script type="text/javascript">newModelForm("direction")</script>
            <hr>
            {% if recipe %}
                <button class="btn custom-btn friendly-btn my-1">Update Recipe</button>
                <a href="{% url 'recipe-detail' recipe.pk %}" class="btn custom-btn danger-btn my-1">Cancel</a>
            {% else %}
                <button class="btn custom-btn friendly-btn my-1">Create Recipe</button>
                <a href="javascript:history.back()" class="btn custom-btn danger-btn my-1">Cancel</a>
            {% endif %}
        </form>
    </div>
{% endblock content %}

recipes/templates/recipes/recipes.html
{% extends "recipes/base.html" %}
{% block content %}
    <div class="container">
        <div class="row row-cols-auto mt-3">
            {% for recipe in recipes %}
                <a href="{% url 'recipe-detail' recipe.pk %}" style="text-decoration: none;">
                    <div class="col">
                        <div class="card mb-3 recipe-card">
                            <img src="{{ recipe.image.url }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{recipe.recipe_name}}</h5>
                                <p class="card-text">{{ recipe.prep_time }}</p>
                            <!--  <a href="{% url 'recipe-detail' recipe.pk %}" class="btn btn-primary">Go somewhere</a> -->
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
            <a href="{% url 'create-recipe' %}" style="text-decoration: none;">
                <div class="col">
                    <div class="card mb-3 mt-2 recipe-card" id="new-recipe-card">
                        <div class="card-img-top">
                            <svg width="60%" height="60%" viewBox="0 0 16 16" class="bi bi-plus-circle" style="margin-left: 20%; margin-top: 20%; margin-bottom: 20%;" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
                                <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
                                <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                            </svg>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title" style="text-align: center; font-size: 2em;">Add New Recipe</h5>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
{% endblock content %}